server:
  port: 8087


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.93.238.228:3357/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: xw@mysql2020




